//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvSitesi.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DboCvEntities : DbContext
    {
        public DboCvEntities()
            : base("name=DboCvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Admin> Tbl_Admin { get; set; }
        public virtual DbSet<Tbl_Deneyimlerim> Tbl_Deneyimlerim { get; set; }
        public virtual DbSet<Tbl_Egitimhayati> Tbl_Egitimhayati { get; set; }
        public virtual DbSet<Tbl_Hakkımda> Tbl_Hakkımda { get; set; }
        public virtual DbSet<Tbl_Mesajlar> Tbl_Mesajlar { get; set; }
        public virtual DbSet<Tbl_Projelerim> Tbl_Projelerim { get; set; }
        public virtual DbSet<Tbl_Sertifikalarim> Tbl_Sertifikalarim { get; set; }
        public virtual DbSet<Tbl_Sosyalmedya> Tbl_Sosyalmedya { get; set; }
        public virtual DbSet<Tbl_Yetenek> Tbl_Yetenek { get; set; }
    }
}
