//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvSitesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Egitimhayati
    {
        public int Id { get; set; }
        public string Okulad { get; set; }
        public string Tur { get; set; }
        public string Bolum { get; set; }
        public string Notort { get; set; }
        public string Tarih { get; set; }
    }
}
