//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvSitesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Deneyimlerim
    {
        public int Id { get; set; }
        public string DeneyimAd { get; set; }
        public string Unvan { get; set; }
        public string İcerik { get; set; }
        public string Tarih { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
