//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvSitesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_Yetenek
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Lütfen Bu Alaný Boþ Geçmeyiniz...")]
        public string Yetenekad { get; set; }
        [Required(ErrorMessage = "Lütfen Bu Alaný Boþ Geçmeyiniz...")]
        [Range(0 , 100 , ErrorMessage ="Girilen Oran 0 ile 100 arasýnda olmalýdýr...")]
        public Nullable<int> oran { get; set; }
    }
}
